package lex;
public enum Tokens {
	id,
	literal_integer, 
	assignment_operator,
	le_operator,
	lt_operator,
	ge_operator,
	gt_operator,
	eq_operator, 
	ne_operator,
	add_operator,
	sub_operator,
	mul_operator,
	div_operator,
	left_paren,
	right_paren,
	function_keyword,
	print_keyword,
	end_keyword,
	while_keyword,
	do_keyword,
	repeat_keyword,
	until_keyword,
	unknown
}
